# Generated by Django 4.2.6 on 2023-11-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('tipo_trabajo', models.CharField(max_length=50)),
                ('tipo_empresa', models.CharField(max_length=50)),
                ('servicio_ofrecido', models.CharField(max_length=200)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
