# Generated by Django 4.2.6 on 2023-11-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_contacto',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
