# Generated by Django 4.2.6 on 2023-11-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_numero_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
