# Generated by Django 4.2.6 on 2023-11-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
