# Generated by Django 4.2.6 on 2023-11-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_contacto',
            field=models.CharField(max_length=20),
        ),
    ]
