# Generated by Django 4.2.6 on 2023-11-27 15:26

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_numero_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut_empresa',
            field=models.CharField(max_length=20, unique=True, validators=[usuarios.models.validate_rut]),
        ),
    ]
