# Generated by Django 4.2.6 on 2023-11-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_rut_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero_contacto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='servicio_ofrecido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_trabajo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='razon_social',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tamano_empresa',
            field=models.CharField(choices=[('microempresa', 'Micro Empresa'), ('pequena', 'Pequeña Empresa'), ('mediana', 'Mediana Empresa'), ('grande', 'Gran Empresa')], default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut_empresa',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_empresa',
            field=models.CharField(choices=[('contratista', 'Contratistas'), ('equipoproviciones', 'Equipo y Proviciones'), ('consultoing', 'Servicios de consultoría e Ingenieria'), ('soporte', 'Servicios de soporte')], max_length=50),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.region')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.comuna'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.provincia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.region'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rubros',
            field=models.ManyToManyField(to='usuarios.rubro'),
        ),
    ]
