# Generated by Django 4.2.6 on 2023-11-28 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_tamano_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tamano_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tamano_empresa'),
        ),
    ]
