# Generated by Django 4.2.7 on 2023-12-01 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_empresa_usuario',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
