# Generated by Django 3.2.3 on 2023-12-01 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_calificacionsitio_contactoproveedor_contactoservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.CreateModel(
            name='InteraccionEmpresa',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('proveedores', models.PositiveIntegerField(default=0)),
                ('servicios', models.PositiveIntegerField(default=0)),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción de Empresa',
                'verbose_name_plural': 'Interacciones de Empresas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedores', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CalificacionSitio',
        ),
        migrations.DeleteModel(
            name='ContactoProveedor',
        ),
        migrations.DeleteModel(
            name='ContactoServicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo_empresa',
        ),
        migrations.AddField(
            model_name='servicio',
            name='servicios',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
