# Generated by Django 4.2.5 on 2023-12-01 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_servicio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
