# Generated by Django 4.2.6 on 2023-12-03 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_servicio_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_proveedores', models.PositiveIntegerField()),
                ('cont_servicios', models.PositiveIntegerField()),
                ('calificacion_sitio', models.PositiveIntegerField()),
                ('terminos_y_condiciones', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
