# Generated by Django 3.2.3 on 2023-12-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_encuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='adj_licitacion',
            field=models.FileField(blank=True, null=True, upload_to='licitaciones/'),
        ),
    ]
